### ISSUE TITLE
Update Riemann to 2.12

### ISSUE THREAD

**Issue by saliceti** [xoebus/riemann-boshrelease#6]
Would you consider bumping Riemann to 2.12? The best feature for us is that it allows us to do batch forwarding to datadog. See: https://github.com/riemann/riemann/blob/ddffd211304bd6e7d1050778611c8a6e14739135/src/riemann/datadog.clj

This is important as we use riemann to forward concourse metrics to datadog and we observed the latency increasing and increasing until no metrics are received anymore.

Batch forwarding solved it for us. This involves building the new jar. We did it manually and used it in that branch: https://github.com/alphagov/paas-riemann-boshrelease/commits/gds_master

**Comment by xoebus** [comment]
Thanks for opening this issue. I don't have access to the `private.yml` for publishing releases for this anymore (so it should probably be moved from my account)! The Concourse core team is able to do this though.

Paging @vito...

**Comment by jmcarp** [comment]
Which gh org do you all think this should live in? Concourse? Cloudfoundry-community?

**Comment by saliceti** [comment]
@vito any chance you could have a look at this?

**Comment by vito** [comment]
@saliceti Sorry. Lost track of this (among many other things) during my recent move.

Related comment: https://github.com/xoebus/riemann-boshrelease/pull/3#issuecomment-281386718 (tl;dr should we just switch back to the upstream repo?)

In the meantime I'll have a look at bumping the package. Your issue mentions building a new jar, but it looks like 0.2.12 is officially out - can we not just grab the tarball? Was it not released at the time you opened this?

**Comment by saliceti** [comment]
Thanks!
