### ISSUE TITLE
Repo is not a valid bosh release

### ISSUE THREAD

**Issue by alamages** [xoebus/riemann-boshrelease#7]
Hello,

We tried to deploy this release as it's mentioned in the how to enable concourse metrics: https://concourse.ci/metrics.html

Unfortunately this does not seem to be a valid bosh release:

```
$ bosh upload release https://github.com/xoebus/riemann-boshrelease
....
  Started extracting release > Extracting release. Failed: Extracting release archive failed. Check task debug log for details. (00:00:00)

Error 30002: Extracting release archive failed. Check task debug log for details.
```
The repo must be a valid tarball in order to be uploaded.

We also tried to use of the existing releases but neither of them worked. They both fail for the following reason:

```
$ bosh upload release https://github.com/xoebus/riemann-boshrelease/archive/v0.4.0.tar.gz
...
  Started downloading remote release > Downloading remote release. Done (00:00:02)

  Started extracting release > Extracting release. Done (00:00:00)

  Started verifying manifest > Verifying manifest. Failed: Release manifest not found (00:00:00)

Error 30003: Release manifest not found

Task 341529 error
```

Was this working in the past for concourse metrics? How can we use this?

**Comment by alamages** [comment]
We actually found that this is uploaded to bosh.io and uploading this works. I think the documentation needs to be updated to point to: https://bosh.io/d/github.com/xoebus/riemann-boshrelease

**Comment by xoebus** [comment]
Merged that PR.
